apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-persistent-volume
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""  # Use an empty string to match the default storage class
  hostPath:
    path: "/mnt/data"  # This is an example path; you should replace it with an appropriate path on your host

